services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: todo-api-go
    ports: 
      - 8080:8080
    volumes:
      - ../:/app
    depends_on: 
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/todo-api-go-db?sslmode=disable

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo-api-go-db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: