name: Docker Build & Push 

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4    

      - name: 'Create env file'
        run: |
          touch .env
          # config
          echo ENV=${{ secrets.ENV }} >> .env
          cat .env

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'


      - name: Configure docker for artifact registry
        run: |
          gcloud auth configure-docker us-docker.pkg.dev

      - name: Build a docker image
        run: docker build -t us-docker.pkg.dev/${{ env.GCP_PROJECT }}/todo-server/todo-server:${GITHUB_SHA::7} .

      - name: Push the docker image
        run: docker push us-docker.pkg.dev/${{ env.GCP_PROJECT }}/todo-server/todo-server:${GITHUB_SHA::7}